name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble build -d:release -Y
      - name: Create package
        shell: bash
        working-directory: ${{runner.workspace}}/ngnim
        env:
          GITHUB_OS: ${{ matrix.os }}
        run: |
          if [ "$GITHUB_OS" == "windows-latest" ];
          then
            tar -cvf ../engge_${{ runner.os }}.tar ngnim.exe
          else
            tar -cvf ../engge_${{ runner.os }}.tar ngnim
          fi
      - name: 📦 Upload package
        uses: actions/upload-artifact@v2
        with:
          name: engge_${{ runner.os }}
          path: ${{runner.workspace}}/engge_${{ runner.os }}.tar
